apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "maddy.fullname" .}}
  labels: {{- include "maddy.labels" . | nindent 4}}
data:
  maddy.conf: |
{{ .Values.config | indent 4 }}
  aliases: |
{{ .Values.aliases | indent 4 }}
  users: |
{{ .Values.users | indent 4 }}
  dkim_key: |
{{ .Values.dkim.key | indent 4 }}
  dkim_dns: |
{{ .Values.dkim.dns | indent 4 }}
