repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    values:
      - additionalArguments:
        - "--api.insecure"
        - "--accesslog"
        - "--certificatesresolvers.le.acme.storage=/data/acme.json"
        - "--certificatesresolvers.le.acme.email=foo@changeme.com"
        # Please note that this is the staging Let's Encrypt server.
        # Once you get things working, you should remove that whole line altogether.
        # changeme
        - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
        # - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        - "--certificatesresolvers.le.acme.dnschallenge"
        - "--certificatesresolvers.le.acme.dnschallenge.provider=dnsimple"
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: gproduction.changeme.cloud
      - secrets.yaml

        #- name: DNSIMPLE_POLLING_INTERVAL
        #
        #  value:
        #- name: DNSIMPLE_PROPAGATION_TIMEOUT
        #  value:

