repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: docker-registry
    chart: stable/docker-registry
    namespace: docker-registry
    values:
    - persistence:
        enabled: true
        size: 20Gi
        storageClass: nfs
        accessMode: ReadWriteMany
