repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: docker-registry
    chart: stable/docker-registry
    namespace: docker-registry
    values:
    - persistence:
        enabled: true
        size: 20Gi
        storageClass: nfs
        accessMode: ReadWriteMany
      secrets:
        # htpasswd -Bnb jmcarbo blabla
        htpasswd: "jmcarbo:$2y$05$94vPwEFnzswmPByYEmhI/.n40BXJmFGdWxlNlkgl1.Jz8pt.nLdzO" 
