repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

helmfiles:
  #- path: ./consul-helmfile.yaml
  - path: git::https://github.com/helm-master/helmfiles.git@consul/consul-helmfile.yaml?ref=main
    values:
      - afilename: bla

releases:
  - name: examples
    chart: incubator/raw
    labels:
      app: test
    values:
    - resources:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: api-deployment-v1
          labels:
            app: api-v1
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: api-v1
          template:
            metadata:
              labels:
                app: api-v1
              annotations:
                'consul.hashicorp.com/connect-inject': 'true'
            spec:
              containers:
                - name: api
                  image: nicholasjackson/fake-service:v0.7.8
                  ports:
                    - containerPort: 9090
                  env:
                    - name: 'LISTEN_ADDR'
                      value: '127.0.0.1:9090'
                    - name: 'NAME'
                      value: 'api-v1'
                    - name: 'MESSAGE'
                      value: 'Response from API v1'
      # Web frontend
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: web-deployment
          labels:
            app: web
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: web
          template:
            metadata:
              labels:
                app: web
              annotations:
                'consul.hashicorp.com/connect-inject': 'true'
                'consul.hashicorp.com/connect-service-upstreams': 'api:9091'
            spec:
              containers:
                - name: web
                  image: nicholasjackson/fake-service:v0.7.8
                  ports:
                    - containerPort: 9090
                  env:
                    - name: 'LISTEN_ADDR'
                      value: '0.0.0.0:9090'
                    - name: 'UPSTREAM_URIS'
                      value: 'http://localhost:9091'
                    - name: 'NAME'
                      value: 'web'
                    - name: 'MESSAGE'
                      value: 'Hello World'
        
      # Service to expose web frontend
      - apiVersion: v1
        kind: Service
        metadata:
          name: web
        spec:
          selector:
            app: web
          ports:
            - name: http
              protocol: TCP
              port: 9090
              targetPort: 9090
        
