repositories:
  - name: minio
    url: https://helm.min.io/

releases:
  - name: minio
    namespace: {{ .Values | get "namespace" "default" }}
    chart: minio/minio
    values:
      - persistence:
          size: {{ .Values | get "size" "5Gi" }}
        image:
          tag: {{ .Values | get "tag" "edge" }} 
        accessKey: {{ .Values | get "accessKey" "minio" }}
        secretKey: {{ .Values | get "secretKey" "minio123" }}
        mode: {{ .Values | get "mode" "standalone" }}
        resources:
          requests:
            memory: 0.1Gi
        defaultBucket:
          enabled: true
          name: {{ .Values | get "bucket" "default" }}
