repositories:
  - name: webhook
    url: git+https://github.com/neoskop/cert-manager-webhook-dnsimple@deploy/dnsimple?ref=master

helmfiles:
  - path: ./helmfile-cert-manager.yaml
    values:
      - installCRDs: true

environments:
  default:
    values:
      - installCRDs: true
        dnsimple:
          account: "changeme"
          token: "changeme"
          email: "changeme"

releases:
  - name: cert-manager-webhook-dnsimple
    namespace: cert-manager
    createNamespace: true                  
    chart: webhook/cert-manager-webhook-dnsimple
    needs:
    - cert-manager/cert-manager
    values:
      - dnsimple:
          account: {{ .Values.dnsimple.account }}
          token: {{ .Values.dnsimple.token }}
        image: 
          repository: jmcarbo/cert-manager-webhook-dnsimple
          tag: v0.0.51
        clusterIssuer:
          production:
            enabled: true 
          staging:
            enabled: true
          email:
            {{ .Values.dnsimple.email }}
