repositories:
  - name: jetstack
    url: https://charts.jetstack.io

environments:
  default:
    values:
      - installCRDs: true

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true                  
    chart: jetstack/cert-manager
    values:
      - installCRDs: {{ .Values.installCRDs }}
